[build]
publish = "public"

[context.deploy-preview.environment]
HUGO_VERSION = "0.116.1"
HUGO_ENABLEGITINFO = "true"
HUGO_ENVIRONMENT = "preview"

[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

